---
# TODO: We should have a config.d or similar setup; this means adding
#       additional services doesn't result in them fighting for control of the
#       same config file.

sources:
    # This maps directly to the API URL
    functional_roles:
        v1:
            # Extracted from the spreadsheet URL
            key: 1c9wehuauQAAegElIRI6vhWktKSI-PcPjHHiXdqASonk

            # Sheet number. Extract from the spreadsheet URL as well.
            gid: 0

            # Base URI for the generation of IDs
            base_uri: "http://vocabulary.unocha.org/FunctionalRole/"

            # Mapping of column names -> API fields
            # Columns that aren't mentioned get ignored.
            mapping:
                "@context": "https://raw.githubusercontent.com/UN-OCHA/taas-data/master/json/v1/functional_roles.jsonld"
                "@id": ID
                label: Preferred Term
                label_fr: French Term
                label_es: Spanish Term
                scope: Scope
