---
# TODO: We should have a config.d or similar setup; this means adding
#       additional services doesn't result in them fighting for control of the
#       same config file.

sources:
    # This maps directly to the API URL
    functional_roles:
        beta-v2:
            url: https://docs.google.com/spreadsheets/d/1c9wehuauQAAegElIRI6vhWktKSI-PcPjHHiXdqASonk/edit#gid=0

            # Mapping of column names -> API fields
            # Columns that aren't mentioned get ignored.
            mapping:
                "@context":
                    type: literal
                    value: https://raw.githubusercontent.com/UN-OCHA/taas-data/master/json/v1/functional_roles.jsonld
                "@id":
                    type: concat
                    prefix: http://vocabulary.unocha.org/FunctionalRole/
                    field: ID

                    # XXX: This shouldn't be optional, but the current dataset
                    #      is missing an ID in the sheet, so it is for now.
                    optional: True

                scope: Scope

                # These all form a language map. See TAAS-16 for more details.
                # https://humanitarian.atlassian.net/browse/TAAS-16
                label.i-default: Preferred Term
                label.en: Preferred Term

                label.fr:
                    field: French Term
                    optional: True

                label.es:
                    field: Spanish Term
                    optional: True

    global_coordination_groups:
        beta-v1:
            url: https://docs.google.com/spreadsheets/d/1SxSircxhXMZCe0PWafCht-whjBdI9UqoeFeSUbiLGc4/edit#gid=0
            mapping:
                id: HRinfo ID
                label: Preferred Term
                acronym: ACRONYM
                group_type: Group Type
                homepage: Homepage

    countries:
        beta-v1:
            url: https://docs.google.com/spreadsheets/d/1NjSI2LaS3SqbgYc0HdD8oIb7lofGtiHgoKKATCpwVdY/edit#gid=1528390745
            mapping:
                id: ID

                iso3:
                    field: ISO 3166-1 Alpha 3-Codes
                    optional: True

                iso2:
                    field: ISO 3166-1 Alpha 2-Codes
                    optional: True

                # Unofficial but generally used fields. These
                # fail over to the ISO-codes if blank.
                x-alpha-2:
                    field:
                        - x Alpha2 codes
                        - ISO 3166-1 Alpha 2-Codes
                    optional: True

                x-alpha-3:
                    field:
                        - x Alpha3 codes
                        - ISO 3166-1 Alpha 3-Codes
                    optional: True

                # The old HRinfo ID, in case people want to match.
                hrinfo_id:
                    field: HRinfo ID
                    optional: True

                # The old ReliefWeb ID, in case people want to match.
                reliefweb_id:
                    field: RW ID
                    optional: True

                # To keep compatibility with the prior HRinfo API.
                admin_level:
                    field: Admin Level
                    optional: True

                m49:
                    field: m49 numerical code
                    optional: True

                # Label is now part of a JSON map, as we expect to add
                # additional label terms in the future for
                # interoperability with various services.

                label.default: Preferred Term

                label.humanitarianresponse:
                    field:
                        - HRinfo Alt Term
                        - Preferred Term

                label.reliefweb-short:
                    field:
                        - RW Short Name
                        - Preferred Term

                label.reliefweb-api:
                    field:
                        - RW API Alt Term
                        - Preferred Term

                label.m49:
                    field:
                        - m49 Alt Term
                        - Preferred Term

                # Lat/Long are presented the same way as they
                # are in HRinfo

                geolocation.lat:
                    field: Latitude
                    optional: True

                geolocation.lon:
                    field: Longitude
                    optional: True

    organization_types:
        beta-v1:
            key: 12nKxos71U6lkttpyYTfwI2bDq9yeN1J7jplHocN96_0
            gid: 0
            mapping:
                id: HR.info ID
                scope: Scope

                label.default: Preferred Term
                label.reliefweb:
                    field: RW Alt Term
                    optional: True

                reliefweb_id:
                    field: RW API ID
                    optional: True

                x-reliefweb-term-is:
                    field: "Match type - RW term is:"
                    optional: True
