---
# TODO: We should have a config.d or similar setup; this means adding
#       additional services doesn't result in them fighting for control of the
#       same config file.

sources:
    # This maps directly to the API URL
    functional_roles:
        v1:
            # Extracted from the spreadsheet URL
            key: 1c9wehuauQAAegElIRI6vhWktKSI-PcPjHHiXdqASonk

            # Sheet number. Obtained from the google spreadsheet URL
            # at the end (`gid=XX`).
            gid: 0

            # Mapping of column names -> API fields
            # Columns that aren't mentioned get ignored.
            mapping:
                "@context":
                    type: literal
                    value: https://raw.githubusercontent.com/UN-OCHA/taas-data/master/json/v1/functional_roles.jsonld
                "@id":
                    type: concat
                    prefix: http://vocabulary.unocha.org/FunctionalRole/
                    field: ID

                    # XXX: This shouldn't be optional, but the current dataset
                    #      is missing an ID in the sheet, so it is for now.
                    optional: True

                scope: Scope

                # These all form a language map. See TAAS-16 for more details.
                # https://humanitarian.atlassian.net/browse/TAAS-16
                label.i-default: Preferred Term
                label.en: Preferred Term

                label.fr:
                    field: French Term
                    optional: True

                label.es:
                    field: Spanish Term
                    optional: True

    countries:
        v1:
            key: 1NjSI2LaS3SqbgYc0HdD8oIb7lofGtiHgoKKATCpwVdY
            gid: 1528390745
            mapping:
                # id and iso3 are in the original "locations" API.
                # https://www.humanitarianresponse.info/api/v1.0/locations
                id: ID

                iso3:
                    field: ISO 3166-3:2013 Alpha 3-Codes
                    optional: True

                # The orignal API codes the ISO-2 code as 'pcode'. We don't.
                iso2:
                    field: ISO 3166-2:2013 Alpha 2-Codes
                    optional: True

                # The old HRinfo ID, in case people want to match.
                hrinfo_id:
                    field: HRinfo ID
                    optional: True

                admin_level:
                    field: Admin Level
                    optional: True

                # We have historical ISO-3166 data, but it does not appear in
                # the original API, has only a single location in our
                # spreadsheet which has a code. Since we're going for a minimum
                # viable product, and ISO standards are complex, we're not
                # publishing it here.

                # m49 code is new with our API.
                m49:
                    field: m49 numerical code
                    optional: True

                # Label is in the original API, but we now have a bunch of
                # alternatives.  We supply a map because that shows semantic
                # association. This is *not* backwards compatible, but makes
                # it very clear that these are all variations of the same name.
                label.default: Preferred Term

                label.humanitarianresponse:
                    field:
                        - HRinfo Alt Term
                        - Preferred Term

                # Reliefweb has *two* different names for countries, depending
                # on where they get used.
                label.reliefweb-name:
                    field:
                        - RW Name Alt Term
                        - Preferred Term

                label.reliefweb-web:
                    field:
                        - RW Website Alt Term
                        - Preferred Term

                label.m49:
                    field:
                        - m49 Alt Term
                        - Preferred Term

                # Lat/Long are a map, these keep backwards compatibility
                # with our old API.
                geolocation.lat:
                    field: Latitude
                    optional: True

                geolocation.lon:
                    field: Longitude
                    optional: True
