---
# TODO: We should have a config.d or similar setup; this means adding
#       additional services doesn't result in them fighting for control of the
#       same config file.

sources:
    # This maps directly to the API URL
    functional_roles:
        v1:
            # Extracted from the spreadsheet URL
            key: 1c9wehuauQAAegElIRI6vhWktKSI-PcPjHHiXdqASonk

            # Sheet number. Obtained from the google spreadsheet URL
            # at the end (`gid=XX`).
            gid: 0

            # Mapping of column names -> API fields
            # Columns that aren't mentioned get ignored.
            mapping:
                "@context":
                    type: literal
                    value: https://raw.githubusercontent.com/UN-OCHA/taas-data/master/json/v1/functional_roles.jsonld
                "@id":
                    type: concat
                    prefix: http://vocabulary.unocha.org/FunctionalRole/
                    field: ID

                    # XXX: This shouldn't be optional, but the current dataset
                    #      is missing an ID in the sheet, so it is for now.
                    optional: True

                scope: Scope

                # These all form a language map. See TAAS-16 for more details.
                # https://humanitarian.atlassian.net/browse/TAAS-16
                label.i-default: Preferred Term
                label.en: Preferred Term

                label.fr:
                    field: French Term
                    optional: True

                label.es:
                    field: Spanish Term
                    optional: True

    organizations:
        v1:
            key: 1oa7Wknz64dMQlV2XsW0ssjh6Gw5SnHVfGxDSw_5eKOQ
            gid: 518938746
            mapping:
                id: HR info ID
                label: Preferred Term
                acronym:
                    type: map
                    field: ACRONYM
                    optional: True
                homepage:
                    type: map
                    field: homepage
                    optional: True
                type:
                    type: link
                    field: OrgTypeID - OrgTypePreferredTerm
                    prefix: https://www.humanitarianresponse.info/en/api/v1.0/organization_types/
                fts_id:
                    type: map
                    field: FinancialTrackingService ID
                    optional: True
